import pandas as pd

def open_csv(file=None,header=6):
    if file:
        #open csv pakai pandas
        data = pd.read_csv(file, header=header)
        #ganti nama header
        data.columns = [
                        "Nama Panggilan", 
                        "Asal Sekolah", 
                        "Jurusan Sekolah", 
                        "Jenis Sekolah",
                        "Jenis Kelas", 
                        "Akreditasi Sekolah", 
                        "Prestasi Sekolah", 
                        "Alumni Sekolah", 
                        "PTN Pilihan I", 
                        "Jurusan Pilihan I di PTN Pilihan I" ,
                        "Jurusan Pilihan II di PTN Pilihan I", 
                        "PTN Pilihan II", 
                        "Jurusan Pilihan I di PTN Pilihan II" ,
                        "Jurusan Pilihan II di PTN Pilihan II", 
                        "Jurusan Diterima", "PTN Diterima", 
                        "Matematika Semester 1", 
                        "Matematika Semester 2", 
                        "Matematika Semester 3", 
                        "Matematika Semester 4", 
                        "Matematika Semester 5", 
                        "Inggris Semester 1", 
                        "Inggris Semester 2", 
                        "Inggris Semester 3", 
                        "Inggris Semester 4", 
                        "Inggris Semester 5",
                        "Indonesia Semester 1",
                        "Indonesia Semester 2",
                        "Indonesia Semester 3",
                        "Indonesia Semester 4",
                        "Indonesia Semester 5",
                        "Fisika Semester 1",
                        "Fisika Semester 2",
                        "Fisika Semester 3",
                        "Fisika Semester 4",
                        "Fisika Semester 5",
                        "Kimia Semester 1",
                        "Kimia Semester 2",
                        "Kimia Semester 3",
                        "Kimia Semester 4",
                        "Kimia Semester 5",
                        "Biologi Semester 1",
                        "Biologi Semester 2",
                        "Biologi Semester 3",
                        "Biologi Semester 4",
                        "Biologi Semester 5",
                        "Ekonomi Semester 1",
                        "Ekonomi Semester 2",
                        "Ekonomi Semester 3",
                        "Ekonomi Semester 4",
                        "Ekonomi Semester 5",
                        "Geografi Semester 1",
                        "Geografi Semester 2",
                        "Geografi Semester 3",
                        "Geografi Semester 4",
                        "Geografi Semester 5",
                        "Sosiologi Semester 1",
                        "Sosiologi Semester 2",
                        "Sosiologi Semester 3",
                        "Sosiologi Semester 4",
                        "Sosiologi Semester 5",
                        "Sejarah Semester 1",
                        "Sejarah Semester 2",
                        "Sejarah Semester 3",
                        "Sejarah Semester 4",
                        "Sejarah Semester 5",
                        "Komputer Semester 1",
                        "Komputer Semester 2",
                        "Komputer Semester 3",
                        "Komputer Semester 4",
                        "Komputer Semester 5",
                        "Peringkat Kelas Semester 1",
                        "Peringkat Kelas Semester 2",
                        "Peringkat Kelas Semester 3",
                        "Peringkat Kelas Semester 4",
                        "Peringkat Kelas Semester 5",
                        "Nilai UN", 
                        "Saran",
                        "Prestasi Lain"
                    ]
        #drop column yang gak digunain
        data = data.drop([
            "Asal Sekolah", 
            "Jenis Kelas",
            "Akreditasi Sekolah", 
            "Prestasi Sekolah", 
            "Alumni Sekolah", 
            "Komputer Semester 1",
            "Komputer Semester 2",
            "Komputer Semester 3",
            "Komputer Semester 4",
            "Komputer Semester 5",
            "Peringkat Kelas Semester 1",
            "Peringkat Kelas Semester 2",
            "Peringkat Kelas Semester 3",
            "Peringkat Kelas Semester 4",
            "Peringkat Kelas Semester 5",
            "Nilai UN", 
            "Saran",
            "Prestasi Lain",
            "Sejarah Semester 1",
            "Sejarah Semester 2",
            "Sejarah Semester 3",
            "Sejarah Semester 4",
            "Sejarah Semester 5",
        ], axis = 1)

        #hapus row jika nama panggilan dan jurusan diterima NaN
        data = data.dropna(subset=["Nama Panggilan"])
    else:
        data = None

    return data